### ISSUE TITLE
Add support to automation-tools functions as actions

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/satellite-populate#33]
```yaml
- action: automation-tools
  name: function_name
  ....
```

Then we can call existing automation tools functions inside the populate datafile
