### ISSUE TITLE
Support calling arbitraty Python functions

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/satellite-populate#34]
Example should be using https://github.com/SatelliteQE/robottelo/blob/master/robottelo/helpers.py#L87

example:

```yaml
- action: register
  log: Get current O.S version using a helper defined in robottelo
  data:
     os_version:
         from_<eval|python|function|callable>: robottelo.helpers.get_os_version()

- model: Repository
  data:
     content_type: ostree
  when: os_version > 6

```
