### ISSUE TITLE
SSH action

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/satellite-populate#37]
Using the robottelo SSH helper or get example from PulpSmash

Implement the action:

```yaml
- action: ssh
   command: ls -la /tmp
   register: tmp_ls_output
   parse_as: json|csv|plain
  auth:
      user:
      password:
      key:
      # omit to use from config
```
