### ISSUE TITLE
Retry option

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/satellite-populate#39]
```yaml
- action: name
  ...
  retry: 
     times: 5
     sleep: 30
  
```

if the above action fails for any reason, retry it 5 more times with sleep interval of 30
